
<?php
$title = 'Neues Rezept hinzufügen';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php

 $form->prepare();

 echo $this->form()->openTag($form);
 //echo $this->formHidden($form->get('id'));

 echo $this->formRow($form->get('Id'));
 echo $this->formRow($form->get('Title'));
 echo $this->formRow($form->get('NoOfPeople'));
 echo $this->formRow($form->get('Kcal'));
 echo $this->formRow($form->get('PublicFlag'));
 echo $this->formRow($form->get('PreparationTime'));
 echo $this->formRow($form->get('CookingTime'));
 echo $this->formRow($form->get('RestingTime'));
 echo $this->formRow($form->get('TypeId'));
 echo $this->formRow($form->get('Level'));
 
 // Add steps
  // redundant code -> check AddRecipeForm
 $maxNumberOfSteps = $form->getMaxNumberOfSteps();;
 $initialSteps = $form->getInitialSteps();
 
 for($i=0;$i<$maxNumberOfSteps;++$i){
     ?><div id="Step<?php echo $i?>">
     
         <div id="singleStep<?php echo $i?>">
          <?php
         echo $this->formRow($form->get('StepQuantityValue'.$i));
         echo $this->formRow($form->get('StepUnit'.$i));
         echo $this->formRow($form->get('StepIngredients'.$i));
         echo $this->formRow($form->get('StepText'.$i));
         ?></div>
         
         <div id="multiStep<?php echo $i?>"><?php 
         echo $this->formRow($form->get('MultiStepSelect'.$i));
         ?></div>
     
     <?php 
     echo $this->formRow($form->get('IsMultiStep'.$i));
     ?>
     </div>
      <?php   
 }

 echo $this->formRow($form->get('StepNumber'));

 echo $this->formRow($form->get('Tipp'));
 echo $this->formSubmit($form->get('Submit'));
 
 echo $this->form()->closeTag();
 
 
 
 ?>

 <style>
.chosen {background-color:lightgray}
</style>
  
 <select class="chosen">
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="opel">Opel</option>
  <option value="audi">Audi</option>
</select>

 <script> 
window.onload = show(2);
 // do not display select for multistep recipes until button pressed
 var i = 0;
 var multiStepSelect = document.getElementById("multiStep"+i);
 while(multiStepSelect != null){
	 multiStepSelect.style.display="none";
	 ++i;
	 multiStepSelect = document.getElementById("multiStep"+i);
 }

</script>

 <script>
 jQuery(document).ready(function(){
		jQuery('.chosen').chosen();
		alert("1");
	});
</script>